In [1]:
import torch
print(torch.__version__)

2.7.1+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


# Creating a Tensor

In [3]:
#using empty
a=torch.empty(2,3)

In [4]:
#check type
type(a)

torch.Tensor

In [5]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.2564, 0.9742, 0.0791],
        [0.8110, 0.4026, 0.7173]])

In [8]:
#use of seed
torch.manual_seed(100)


In [9]:
#using rand
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
#using rand
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#other ways

#arange
print("using arange -> ",torch.arange(0,10))
print("using arange -> ",torch.arange(0,10,2))

using arange ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using arange ->  tensor([0, 2, 4, 6, 8])


In [13]:
#using linespace
print("using linspace -> ",torch.linspace(0,10,10))

using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [14]:
#using eye
print("using eye -> ",torch.eye(5))

using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [15]:
#using full
print("using full -> ",torch.full((3,2),5))

using full ->  tensor([[5, 5],
        [5, 5],
        [5, 5]])


# Tensor Shapes

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
#Empty_Like
torch.empty_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [19]:
#Zeros_Like
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [20]:
#ones_Like
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
#rand_like
torch.rand_like(x)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Tensor Data Types

In [22]:
x.dtype

torch.float64

In [23]:
y=torch.tensor([1.0,2.0,3.0],dtype=torch.int32)
print(y)
y.dtype

tensor([1, 2, 3], dtype=torch.int32)


torch.int32

In [24]:
#using to()
y=y.to(torch.float32)
y.dtype

torch.float32

# Mathematical Operations

## 1. Scalar Operations

In [25]:
x=torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [26]:
#addition
x+2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [27]:
#substraction
x-2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [28]:
#multiplication
x*3

tensor([[0.6717, 0.9070],
        [0.5353, 2.4715]])

In [29]:
#division
x/3

tensor([[0.0746, 0.1008],
        [0.0595, 0.2746]])

In [30]:
# int division
(x*100)//3

tensor([[ 7., 10.],
        [ 5., 27.]])

In [31]:
#mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 1.]])

In [32]:
#power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

## 2. Element wise operation

In [33]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [34]:
#add
a+b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [35]:
#sub
a-b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [36]:
#multiply
a*b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [37]:
#division
a/b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [38]:
#power
a**b

tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])

In [39]:
#mod
a%b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [40]:
c=torch.tensor([1,-2,3,-4])

In [41]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [42]:
#negative
torch.neg(a)

tensor([[-0.5557, -0.9770, -0.4440],
        [-0.9478, -0.7445, -0.4892]])

In [43]:
#round
torch.round(a)

tensor([[1., 1., 0.],
        [1., 1., 0.]])

In [44]:
#ceil
torch.ceil(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [45]:
#floor
torch.floor(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [47]:
#clamp
torch.clamp(a,min=2,max=3)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

## 3. Reduction operation

In [53]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float64)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]], dtype=torch.float64)

In [54]:
#sum
torch.sum(e)

tensor(42., dtype=torch.float64)

In [55]:
#sum along columns
torch.sum(e,dim=0)

tensor([14., 16., 12.], dtype=torch.float64)

In [56]:
#sum alomg rows
torch.sum(e,dim=1)

tensor([17., 25.], dtype=torch.float64)

In [57]:
#mean
torch.mean(e)

tensor(7., dtype=torch.float64)

In [58]:
torch.mean(e,dim=0)

tensor([7., 8., 6.], dtype=torch.float64)

In [59]:
#median
torch.median(e)

tensor(7., dtype=torch.float64)

In [60]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(9., dtype=torch.float64)
tensor(5., dtype=torch.float64)


In [62]:
# product
torch.prod(e)

tensor(99225., dtype=torch.float64)

In [63]:
# standard deviation
torch.std(e)

tensor(1.7889, dtype=torch.float64)

In [64]:
#variance
torch.var(e)

tensor(3.2000, dtype=torch.float64)

In [65]:
#argmax
torch.argmax(e)

tensor(3)

In [66]:
#argmin
torch.argmin(e)

tensor(0)

## 4. Matrix operations

In [67]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [68]:
# matrix multiplication
torch.matmul(f,g)

tensor([[137, 117],
        [139, 130]])

In [69]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
#dot product
torch.dot(vector1,vector2)

tensor(11)

In [70]:
#transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [74]:
#determinant
x=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(x)
torch.det(x)

tensor([[7., 2., 3.],
        [8., 5., 6.],
        [2., 9., 5.]])


tensor(-73.)

In [75]:
#inverse
torch.inverse(x)

tensor([[ 0.3973, -0.2329,  0.0411],
        [ 0.3836, -0.3973,  0.2466],
        [-0.8493,  0.8082, -0.2603]])

## 5. Comparision operations

In [76]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[0, 4, 2],
        [7, 1, 1]])
tensor([[5, 4, 4],
        [1, 1, 2]])


In [77]:
# greater than
i>j

tensor([[False, False, False],
        [ True, False, False]])

In [78]:
# less than
i<j

tensor([[ True, False,  True],
        [False, False,  True]])

In [80]:
# equal to
i == j

tensor([[False,  True, False],
        [False,  True, False]])

In [82]:
# not equal to
i != j

tensor([[ True, False,  True],
        [ True, False,  True]])

In [ ]:
# greater than equal to

# less than equal to


## 6. Special functions

In [89]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[4., 5., 6.],
        [9., 2., 3.]])

In [90]:
#log 
torch.log(k)

tensor([[1.3863, 1.6094, 1.7918],
        [2.1972, 0.6931, 1.0986]])

In [91]:
# exp
torch.exp(k)

tensor([[5.4598e+01, 1.4841e+02, 4.0343e+02],
        [8.1031e+03, 7.3891e+00, 2.0086e+01]])

In [92]:
#sqrt
torch.sqrt(k)

tensor([[2.0000, 2.2361, 2.4495],
        [3.0000, 1.4142, 1.7321]])

In [93]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9933, 0.9975],
        [0.9999, 0.8808, 0.9526]])

In [94]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.0067, 0.9526, 0.9526],
        [0.9933, 0.0474, 0.0474]])

In [95]:
#relu
torch.relu(k)

tensor([[4., 5., 6.],
        [9., 2., 3.]])

# Inplace Operations

In [96]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])


In [97]:
m.add_(n)

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [98]:
m

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [99]:
n

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [100]:
torch.relu(m)

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [101]:
m.relu_()

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

# Copying a Tensor

In [102]:
a=torch.rand(2,3)
a

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [103]:
b=a
b[0][0]=0

In [104]:
a

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [105]:
b=a.clone()
b[0][0]=3

In [106]:
b

tensor([[3.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [107]:
a

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [108]:
id(a)

2954035445536

In [109]:
id(b)

2954035219264

# Tensor Operations on GPU

In [110]:
torch.cuda.is_available()

False

In [111]:
device=torch.device('cuda')

In [112]:
# creating a new tensor on gpu
torch.rand((2,3),device=device)

AssertionError: Torch not compiled with CUDA enabled

# Reshaping Tensors

In [114]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [115]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [117]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
b=torch.rand(2,3,4)
b

tensor([[[0.5534, 0.2682, 0.9556, 0.9761],
         [0.5934, 0.3124, 0.9431, 0.8519],
         [0.9815, 0.1132, 0.4783, 0.4436]],

        [[0.3847, 0.4521, 0.5569, 0.9952],
         [0.0015, 0.0813, 0.4907, 0.2130],
         [0.4603, 0.1386, 0.0277, 0.5662]]])

In [124]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [123]:
b.shape

torch.Size([2, 3, 4])

In [125]:
#unsqueeze
# image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [128]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy to Pytorch and vice versa